# Generated by Django 6.0 on 2026-01-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_convert_department_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
