# Generated by Django 6.0 on 2026-01-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_college_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
