# Generated by Django 6.0 on 2026-01-24 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0006_add_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAffiliatedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_programs', to='accounts.college')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_colleges', to='academic.program')),
            ],
            options={
                'unique_together': {('college', 'program')},
            },
        ),
    ]
