# Generated by Django 6.0 on 2026-01-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_program_department'),
        ('accounts', '0007_collegeaffiliatedprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='faculty', to='academic.department'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('hod', 'Head of Department'), ('principal', 'Principal')], default='faculty', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
