# Generated by Django 6.0 on 2026-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_facultyprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
