# Generated by Django 6.0 on 2026-01-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_examnotification_examsubject_questionpaper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('is_elective', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_semesters', to='academic.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='academic.program')),
            ],
            options={
                'ordering': ['program', 'semester', 'course__code'],
                'unique_together': {('program', 'semester', 'course')},
            },
        ),
    ]
